### ISSUE TITLE
feat: allow specifying an interface to inherit for generated token classes

### ISSUE THREAD

**Issue by timcreatedit** [whynotmake-it/figmage#191]
**Description**

Sometimes you want the generated classes to inherit a certain interface that might be coming from within the app, or another package.

e.g.

```dart
import 'package:my_app/core/my_colors.dart';

class ColorsSemantic extends ThemeExtension<ColorsMyCollection> implements MyColors {
 // ...
}
```

We should allow for configuring this **per collection**.

This could look something like this:

```yaml
fileId: "YOUR_FIGMA_FILE_ID"
packageName: "design_tokens"
asPackage: false
colors:
  from:
    - "semantic/colors"
  implements:
    - collections: ["semantic"] # empty list would mean the following interface settings apply to all collections
      interfaces:
        - name: "MyColors"
          import: "package:my_app/core/my_colors.dart"

```

**Requirements**

- [ ] Any collection can specify multiple interfaces to implement
- [ ] Generated code just naively adds the import and the `implements`, no checks are performed
- [ ] pubspec.yaml edits are out of scope here (using this in a generated package might be frustrating at first)
